include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Button Automation
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
PKG_MAINTAINER:=洛夕

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
