include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2
PKG_RELEASE:=9
LUCI_TITLE:=LuCI support for Home Dashboard
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
PKG_MAINTAINER:=洛夕

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
