#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: 源码更新检查器
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: 更新检查器

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 获取 Commit 哈希
        id: getHash
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: 对比 Commit 哈希
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: commitHash_${{ steps.getHash.outputs.commitHash }}

      - name: 保存新 Commit 哈希
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: 触发构建
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          event-type: Source Code Update
          client-payload: '{"device": "256M", "repo": "https://github.com/padavanonly/immortalwrt-mt798x-6.6"}'

      - name: 删除工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 2
